FROM node:16-alpine

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm install

EXPOSE 3001

COPY . .

RUN apk update && apk add bash

RUN npx prisma generate --schema src/database/prisma/schema.dev.prisma
