version: '3.9'

services:
  db:
    image: mysql:latest
    container_name: db
    ports:
      - 3307:3306
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    restart: 'always'
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"] # Deve aguardar o banco ficar operacional
      timeout: 10s
      retries: 5
    cap_add:
      - SYS_NICE # Deve omitir alertas menores

  backend:
    build: .
    depends_on:
      db:
        condition: service_healthy
    environment:
      - NODE_ENV=test
      - DATABASE_URL_TEST=mysql://root:123456@db/project-manager-test?schema=public
      - JWT_SECRET=20bf2315aa8fba365f91b02b3d3fe769
      - TOKEN_ADMIN=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbkRhdGEiOnsiZW1haWwiOiJzaW1wc29uQGdtYWlsLmNvbSJ9LCJpYXQiOjE2NDg0NjcxODgsImV4cCI6MTY4MDAwMzE4OH0.7kXO5Lx0ofsZfV07ii-OhRrG0WNPz5JunCBye2wcAU
    healthcheck:
      test: ["CMD", "lsof", "-t", "-i:3001"] # Caso utilize outra porta interna para o back, altere ela aqui também
      timeout: 10s
      retries: 5
