version: '3.9'

services:
  db:
    image: mysql:latest
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      timeout: 10s
      retries: 5
      start_period: 30s
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3307:3306
    environment:
      - MYSQL_ROOT_PASSWORD=password

  test:
    build: .
    restart: always
    environment:
      - DATABASE_URL_TEST=mysql://root:password@db:3306/project_manager_test
      - JWT_SECRET="20bf2315aa8fba365f91b02b3d3fe769"
    depends_on:
      db:
        condition: service_healthy
