on: [pull_request]

jobs:
  eslint:
    runs-on: ubuntu-20.04
    steps:
      - name: Verifica o repositório do Git
        uses: actions/checkout@v2

      - name: Instala o node com a versão 16
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Instalando as dependências
        run: npm install

      - name: Executando o lint para verificar se há erros
        run: npx eslint . --ext .ts

  tests:
    runs-on: ubuntu-20.04
    needs: [eslint]
    steps:
      - name: Verifica o repositório do Git
        uses: actions/checkout@v2

      - name: Sobe os containers
        run: docker-compose up --build -d

      - name: Roda os testes de integração
        run: docker-compose exec -T backend npm test

      - name: Roda os testes unitarios
        run: docker-compose exec -T backend npm run test:unit

      - name: Derruba os containers
        if: always()
        run: docker-compose down --rmi all --volumes --remove-orphans
